
name: 'jaffle_shop'
version: '0.1'
profile: 'jaffle_shop'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view

snapshots:
  jaffle_shop:
    orders_snapshot:
      +materialized: view
      +hours_to_expiration: 6
      +unique_key: id
      +strategy: timestamp
      +order_date: order_date
  customers_snapshot:
      +materialized: view
      +hours_to_expiration: 6
      +unique_key: id
      +strategy: check
      +check_cols: [id]