version: 2

sources:
  - name: jaffle_shop
    database: dbt-tutorial
    freshness:
      warn_after: {count: 7, period: day}
      error_after: {count: 30, period: day}
    tables:
      - name: customers
      - name: orders
        max_loaded_at: cast(order_date as timestamp)
        loaded_at_field: cast(order_date as timestamp)
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: status
            tests:
              - accepted_values:
                  values: ['placed', 'shipped', 'completed', 'returned', 'return_pending']
      - name: raw_payments

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'returned']

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']

exposures:
  - name: stg_orders
    type: dashboard
    maturity: medium
    url: https://github.com/ynambiar/jaffle_shop
    description: An exposure of Jaffle Shop orders.
    depends_on:
      - ref('stg_orders')
    owner:
      name: Yamini Nambiar
      email: yamini.nambiar@dbtlabs.com